# SPDX-FileCopyrightText: © opening_hours.js contributors
# SPDX-License-Identifier: CC0-1.0
---

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: quarterly
    cooldown:
      default-days: 7
    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
