# SPDX-FileCopyrightText: © opening_hours.js contributors
# SPDX-License-Identifier: CC0-1.0
---

extends: default

ignore: |
  node_modules
  submodules
  src/holidays/nominatim_cache/

rules:
  line-length:
    max: 1000
    level: warning
