---
# SPDX-FileCopyrightText: © 2021 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: CC0-1.0

name: Continuous Integration

"on":
  - "push"
  - "pull_request"

permissions:
  contents: read
  pull-requests: read

env:
  npm_config_cache: /tmp/npm-cache
  npm_config_min_release_age: 7
  NODE_OPTIONS: --use-system-ca

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: "Use Node.js"
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run linter tests
        run: npm run lint

  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v6

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: wagoid/commitlint-github-action@v6

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Use latest Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
      - id: npm-cache
        name: Restore npm cache
        uses: actions/cache@v6
        with:
          key: npm-cache-${{ github.ref_name }}
          path: ${{ env.npm_config_cache }}
      - name: Install dependencies
        run: make dependencies-get
      - name: Build
        run: make build
      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: opening-hours-build
          path: build/

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          # Support policy: We support every Node.js version that is still "maintained".
          # See: https://nodejs.org/en/about/releases/
          - "22.x"
          - "24.x"
          - "26.x"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Download build artifact
        uses: actions/download-artifact@v6
        with:
          name: opening-hours-build
          path: build/
      - name: Mark build artifact as current
        run: touch build/*
      - name: Run full test suite
        run: make check-all
